QuantLib::PricingEngine* qlBinomialVanillaEngineAux(int tree, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps);
QuantLib::PricingEngine* qlBinomialConvertibleEngineAux(int tree, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps);

QuantLib::PricingEngine* qlMCVarianceSwapEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCHestonHullWhiteEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::HybridHestonHullWhiteProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, int controlVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCAmericanEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, int controlVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed, unsigned polynomOrder, QuantLib::LsmBasisSystem::PolynomType polynomType, unsigned nCalibrationSamples);
QuantLib::PricingEngine* qlMCBarrierEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, int isBiased, unsigned seed);
QuantLib::PricingEngine* qlMCDigitalEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> x0, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCDiscreteArithmeticAPEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, int controlVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCDiscreteArithmeticASEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCDiscreteGeometricAPEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCEuropeanEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCEuropeanGJRGARCHEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GJRGARCHProcess> x0, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCEuropeanHestonEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::HestonProcess> x0, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCHullWhiteCapFloorEngine1Aux(int rngtrait, QuantLib::ext::shared_ptr<QuantLib::HullWhite> model, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCPerformanceEngine1Aux(int rngtrait, const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);

QuantLib::PricingEngine* qlFdBlackScholesVanillaEngineAux(const QuantLib::ext::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned tGrid, unsigned xGrid, unsigned dampingSteps, const QuantLib::FdmSchemeDesc &fdScheme);

/* vim: set ft=cpp ff=unix ts=8 sts=2 sw=2 et: */
