cabal-version:      >=1.10
name:               hasquant
version:            0.2.0.0
synopsis:           Bindings to QuantLib
-- description:
-- bug-reports:
-- license:
-- license-file:        LICENSE
author:             Sergey Khorev
maintainer:         sergey.khorev@gmail.com
-- copyright:
category:           Finance
build-type:         Simple
-- extra-source-files:  cbits
-- stackage lts-18.5 (GHC-8.10.4). also tested with lts-15.3 (ghc-8.8.2), lts-16.31 (ghc-8.8.4), lts-14.27 (ghc-8.6.5), lts-13.11 (ghc-8.6.3),
-- lts-12.14 (ghc-8.4.3), lts-11.22 (ghc-8.2.2), lts-7.24 (ghc-8.0.1)
-- used to work with lts-6.35 (ghc-7.10.3) until I started using TemplateHaskell (there is no BangType in GHC-7.x and I'm too lazy to work around this)
-- tested-with:        GHC==8.10

flag buildExample
  Default: False

flag trackAllocations
  Default: False

library
-- the order is important as it defines the order of preprocessing modules with c2hs
  exposed-modules:  QuantLib.Type
                    , QuantLib.Utility
                    , QuantLib.Math
                    , QuantLib.Currency
                    , QuantLib.Time.Date
                    , QuantLib.Time.Calendar
                    , QuantLib.Time.Schedule
                    , QuantLib.Settings
                    , QuantLib.InterestRate
                    , QuantLib.Index
                    , QuantLib.Instrument
                    , QuantLib.Quote
                    , QuantLib.TermStructure
                    , QuantLib.TermStructure.Yield
                    , QuantLib.TermStructure.Credit
                    , QuantLib.TermStructure.Volatility
                    , QuantLib.Index.InterestRate
                    , QuantLib.CashFlow
                    , QuantLib.Instrument.Bond
                    , QuantLib.Instrument.CapFloor
                    , QuantLib.Instrument.Forward
                    , QuantLib.Process
                    , QuantLib.Instrument.Option
                    , QuantLib.Model
                    , QuantLib.Instrument.Credit
                    , QuantLib.Instrument.Swap
                    , QuantLib.PricingEngine

  other-modules:    QuantLib.Internal
                    , QuantLib.Internal.Enum
                    , QuantLib.Internal.Calendar
                    , QuantLib.Internal.Schedule
                    , QuantLib.Internal.CashFlow
                    , QuantLib.Internal.Index
                    , QuantLib.Internal.InterestRate
                    , QuantLib.Internal.Quote
                    , QuantLib.Internal.TermStructure
                    , QuantLib.Internal.Currency
                    , QuantLib.Internal.Syntax
                    , QuantLib.Internal.CalendarEnum
  -- other-extensions:
  build-depends:    base >=4.9 && <5.0
                    , time
                    , template-haskell
                    , split
  -- hs-source-dirs:
  build-tools:      c2hs

  if impl(ghc < 8.10)
    -- some versions of c2hs didn't like line markers like "# 0" in generated .i files. Guarding with impl because current ghcide seems to be confused by the flag while everything else works just fine
    cpp-options:      -P

  default-language: Haskell2010
  c-sources:        cbits/qlBond.cpp
                    , cbits/qlCalendar.cpp
                    , cbits/qlCouponPricer.cpp
                    , cbits/qlCredit.cpp
                    , cbits/qlCurrency.cpp
                    , cbits/qlDate.cpp
                    , cbits/qlDayCounter.cpp
                    , cbits/qlDefaultTS.cpp
                    , cbits/qlForward.cpp
                    , cbits/qlIborIndex.cpp
                    , cbits/qlIndex.cpp
                    , cbits/qlInstrument.cpp
                    , cbits/qlInterestRate.cpp
                    , cbits/qlLeg.cpp
                    , cbits/qlMath.cpp
                    , cbits/qlMethod.cpp
                    , cbits/qlModel.cpp
                    , cbits/qlOption.cpp
                    , cbits/qlPeriod.cpp
                    , cbits/qlPricingEngineAux.cpp
                    , cbits/qlPricingEngine.cpp
                    , cbits/qlProcess.cpp
                    , cbits/qlQuote.cpp
                    , cbits/qlSchedule.cpp
                    , cbits/qlSettings.cpp
                    , cbits/qlSwap.cpp
                    , cbits/qlTSAux.cpp
                    , cbits/qlUtilities.cpp
                    , cbits/qlVolatilityTS.cpp
                    , cbits/qlYieldTS.cpp
  if flag(trackAllocations)
    cc-options:        -Wall -Wextra -pedantic -DQLTRACK_ALLOCATIONS
  else
    cc-options:        -Wall -Wextra -pedantic

  include-dirs:     cbits

  ghc-options:      -Wall -Wredundant-constraints -Wmissing-exported-signatures -Widentities

  extra-libraries:  QuantLib stdc++

executable hasquant_example
  if flag(buildExample)
    buildable: True
  else
    buildable: False

  main-is:          QuantLib/MainExample.hs
  other-modules:    QuantLib.Example.FRA
                    , QuantLib.Example.Bond
                    , QuantLib.Example.Repo
                    , QuantLib.Example.Swap
                    , QuantLib.Example.FittedBondCurve
                    , QuantLib.Example.CDS
                    , QuantLib.Example.BermudanSwaption
                    , QuantLib.Example.Replication
                    , QuantLib.Example.CallableBond
                    , QuantLib.Example.ConvertibleBond
                    , QuantLib.Example.EquityOption
  ghc-options:      -Wall
  build-depends:    base >= 4.9 && < 5.0
                    , time
                    , hasquant
  default-language: Haskell2010
  hs-source-dirs:   test

test-suite hasquant_test
  type:             exitcode-stdio-1.0
  main-is:          QuantLib/MainTest.hs
  other-modules:    QuantLib.Example.FRA
                    , QuantLib.Example.Bond
                    , QuantLib.Example.Repo
                    , QuantLib.Example.Swap
  ghc-options:      -Wall
  build-depends:    base >= 4.9 && < 5.0
                    , time
                    , hspec
                    , HUnit
                    , QuickCheck
                    , hasquant
  default-language: Haskell2010
  hs-source-dirs:   test

-- vim: set et ts=8 sts=2 sw=2:
