name: hasquant
version: "0.3.0.0"
synopsis: Bindings to QuantLib
license: BSD-3-Clause
maintainer: Sergei Khorev <sergey.khorev@gmail.com>
copyright: (c) 2012-2026 Sergei Khorev
category: Finance
description: |
  Bindings to the QuantLib library.
build-type: Simple
github: khorser/hasquant
tested-with:
  - GHC == 8.10.6 # lts-18.8
  - GHC == 9.10.3 # lts-24.53
language: Haskell2010
flags:
  buildExample:
    default: False
    manual: True
  trackAllocations:
    default: False
    manual: True
  usePkgConfig:
    default: True
    manual: True
extra-source-files:
  - cbits/*.h
dependencies:
  - base >=4.11 && <5.0
  - time
ghc-options: -Wall -Wredundant-constraints -Wmissing-exported-signatures -Widentities
when:
  - condition: flag(trackAllocations)
    ghc-options: -g3

library:
  dependencies:
    - template-haskell
    - vector
  verbatim:
    - build-tool-depends: c2hs:c2hs
  exposed-modules: # the order is important as it defines the order used by c2hs
    - QuantLib.Type
    - QuantLib.Math
    - QuantLib.Currency
    - QuantLib.Time.Date
    - QuantLib.Time.Calendar
    - QuantLib.Time.Schedule
    - QuantLib.Settings
    - QuantLib.InterestRate
    - QuantLib.Index
    - QuantLib.Instrument
    - QuantLib.Quote
    - QuantLib.Method
    - QuantLib.CashFlow
    - QuantLib.TermStructure
    - QuantLib.TermStructure.Yield
    - QuantLib.TermStructure.Inflation
    - QuantLib.TermStructure.Credit
    - QuantLib.TermStructure.Volatility
    - QuantLib.Index.InterestRate
    - QuantLib.Index.Inflation
    - QuantLib.Index.Equity
    - QuantLib.Instrument.Bond
    - QuantLib.Instrument.CapFloor
    - QuantLib.Instrument.Forward
    - QuantLib.Process
    - QuantLib.Instrument.Option
    - QuantLib.Model
    - QuantLib.Instrument.Credit
    - QuantLib.Instrument.Swap
    - QuantLib.PricingEngine
    - QuantLib.Syntax
  other-modules:
    - QuantLib.Internal
    - QuantLib.Internal.Enum
    - QuantLib.Internal.Syntax
    - QuantLib.Internal.CalendarEnum
    - QuantLib.Internal.Type
  cxx-sources:
    - cbits/*.cpp
  include-dirs: cbits
  cxx-options: -Wall -Wextra -pedantic -std=c++17
  when:
    - condition: "!os(windows)"
      extra-libraries: stdc++
    - condition: flag(trackAllocations) && os(osx)
      cxx-options: -DQLTRACK_ALLOCATIONS="/dev/fd/2"
    - condition: flag(trackAllocations) && os(linux)
      cxx-options: -DQLTRACK_ALLOCATIONS="/proc/self/fd/2"
    - condition: impl(ghc < 8.10)
      cpp-options: -P # some c2hs versions didn't like line markers like "# 0" in generated .i files
    - condition: flag(usePkgConfig) && !os(windows)
      then:
        pkg-config-dependencies:
          quantlib >= 1.43
      else:
        extra-libraries: QuantLib
    - condition: os(osx)
      include-dirs: /opt/homebrew/include

tests:
  hasquant_test:
    main: QuantLib/MainTest.hs
    source-dirs:
      - test
      - main/test
    dependencies:
      - hasquant
      - hspec
      - HUnit
      - QuickCheck

executables:
  hasquant_example:
    main: QuantLib/MainExample.hs
    source-dirs:
      - test
      - main/exe
    dependencies:
      - hasquant
    when:
      - condition: flag(buildExample)
        then:
          buildable: True
        else:
          buildable: False
