name: hasquant
version: "0.2.5.0"
synopsis: Bindings to QuantLib
license: BSD-3-Clause
maintainer: Sergey Khorev <sergey.khorev@gmail.com>
copyright: (c) 2012-2022 Sergey Khorev
category: Finance
description: |
  Bindings to the QuantLib library.
github: khorser/hasquant
tested-with:
  - GHC == 8.10.6 # lts-18.8
  - GHC == 9.0.2 # lts-19.32
  - GHC == 9.2.5 # lts-20.0
  #- GHC == 8.10.4 # lts-18.5
  #- GHC == 8.8.4  # lts-16.31
  #- GHC == 8.8.2  # lts-15.3
  #- GHC == 8.6.5  # lts-14.27
  #- GHC == 8.6.3  # lts-13.11
  # for ghc < 8.10 you need to add -P to cpp-options because some c2hs versions didn't like line markers like "# 0" in generated .i files
  # also used to work with lts-6.35 (ghc-7.10.3) until I started using TemplateHaskell:
  # there is no BangType in GHC-7.x and I can't be bothered with maintaining the compatibility
language: Haskell2010
flags:
  buildExample:
    default: False
    manual: True
  trackAllocations:
    default: False
    manual: True
extra-source-files:
  - cbits/*.h

library:
  ghc-options: -Wall -Wredundant-constraints -Wmissing-exported-signatures -Widentities
  dependencies:
    - base >=4.9 && <5.0
    - time
    - template-haskell
    - split
    - vector
  verbatim:
    - build-tool-depends: c2hs:c2hs
  exposed-modules: # the order is important as it defines the order used by c2hs
    - QuantLib.Type
    - QuantLib.Math
    - QuantLib.Currency
    - QuantLib.Time.Date
    - QuantLib.Time.Calendar
    - QuantLib.Time.Schedule
    - QuantLib.Settings
    - QuantLib.InterestRate
    - QuantLib.Index
    - QuantLib.Instrument
    - QuantLib.Quote
    - QuantLib.Method
    - QuantLib.TermStructure
    - QuantLib.TermStructure.Yield
    - QuantLib.TermStructure.Credit
    - QuantLib.TermStructure.Volatility
    - QuantLib.Index.InterestRate
    - QuantLib.CashFlow
    - QuantLib.Instrument.Bond
    - QuantLib.Instrument.CapFloor
    - QuantLib.Instrument.Forward
    - QuantLib.Process
    - QuantLib.Instrument.Option
    - QuantLib.Model
    - QuantLib.Instrument.Credit
    - QuantLib.Instrument.Swap
    - QuantLib.PricingEngine
    - QuantLib.Syntax
  other-modules:
    - QuantLib.Internal
    - QuantLib.Internal.Enum
    - QuantLib.Internal.Syntax
    - QuantLib.Internal.CalendarEnum
    - QuantLib.Internal.Type
  extra-libraries:
    - QuantLib
    - stdc++
  cxx-sources:
    - cbits/*.cpp
  include-dirs: cbits
  when:
    - condition: flag(trackAllocations)
      then: # log allocations to stderr
        cxx-options: -Wall -Wextra -pedantic -DQLTRACK_ALLOCATIONS="/proc/self/fd/2"
      else:
        cxx-options: -Wall -Wextra -pedantic
tests:
  hasquant_test:
    dependencies:
      - base >= 4.9 && < 5.0
      - time
      - hspec
      - HUnit
      - QuickCheck
      - hasquant
    ghc-options: -Wall
    source-dirs:
      - test
      - main/test
    main: QuantLib/MainTest.hs

executables:
  hasquant_example:
    when:
      - condition: flag(buildExample)
        then:
          buildable: True
        else:
          buildable: False
    ghc-options: -Wall
    dependencies:
      - base >= 4.9 && < 5.0
      - time
      - hasquant
    source-dirs:
      - test
      - main/exe
    main: QuantLib/MainExample.hs
