name: hasquant
version: "0.2.6.0"
synopsis: Bindings to QuantLib
license: BSD-3-Clause
maintainer: Sergei Khorev <sergey.khorev@gmail.com>
copyright: (c) 2012-2022 Sergey Khorev
category: Finance
description: |
  Bindings to the QuantLib library.
build-type: Simple
github: khorser/hasquant
tested-with:
  - GHC == 8.10.6 # lts-18.8
  - GHC == 9.0.2 # lts-19.32
  - GHC == 9.2.5 # lts-20.2
  #- GHC == 8.10.4 # lts-18.5
  #- GHC == 8.8.4  # lts-16.31
  # with minimal compatibility tweaks in Quantlib.Internal.Syntax and probably other modules you should be able to build it with GHC 7.10
language: Haskell2010
flags:
  buildExample:
    default: False
    manual: True
  trackAllocations:
    default: False
    manual: True
  usePkgConfig:
    default: True
    manual: True
extra-source-files:
  - cbits/*.h
dependencies:
  - base >=4.11 && <5.0
  - time

library:
  ghc-options: -Wall -Wredundant-constraints -Wmissing-exported-signatures -Widentities
  dependencies:
    - template-haskell
    - split
    - vector
  verbatim:
    - build-tool-depends: c2hs:c2hs
  exposed-modules: # the order is important as it defines the order used by c2hs
    - QuantLib.Type
    - QuantLib.Math
    - QuantLib.Currency
    - QuantLib.Time.Date
    - QuantLib.Time.Calendar
    - QuantLib.Time.Schedule
    - QuantLib.Settings
    - QuantLib.InterestRate
    - QuantLib.Index
    - QuantLib.Instrument
    - QuantLib.Quote
    - QuantLib.Method
    - QuantLib.TermStructure
    - QuantLib.TermStructure.Yield
    - QuantLib.TermStructure.Credit
    - QuantLib.TermStructure.Volatility
    - QuantLib.Index.InterestRate
    - QuantLib.CashFlow
    - QuantLib.Instrument.Bond
    - QuantLib.Instrument.CapFloor
    - QuantLib.Instrument.Forward
    - QuantLib.Process
    - QuantLib.Instrument.Option
    - QuantLib.Model
    - QuantLib.Instrument.Credit
    - QuantLib.Instrument.Swap
    - QuantLib.PricingEngine
    - QuantLib.Syntax
  other-modules:
    - QuantLib.Internal
    - QuantLib.Internal.Enum
    - QuantLib.Internal.Syntax
    - QuantLib.Internal.CalendarEnum
    - QuantLib.Internal.Type
  cxx-sources:
    - cbits/*.cpp
  include-dirs: cbits
  cxx-options: -Wall -Wextra -pedantic -std=c++17
  extra-libraries: stdc++
  when:
    - condition: flag(trackAllocations) # log allocations to stderr
      cxx-options: -DQLTRACK_ALLOCATIONS="/proc/self/fd/2"
    - condition: impl(ghc < 8.10)
      cpp-options: -P # some c2hs versions didn't like line markers like "# 0" in generated .i files
    - condition: flag(usePkgConfig) && !os(windows)
      then:
        pkg-config-dependencies:
          quantlib >= 1.43
      else:
        extra-libraries: QuantLib
    - condition: os(osx)
      include-dirs: /opt/homebrew/include
tests:
  hasquant_test:
    dependencies:
      - hspec
      - HUnit
      - QuickCheck
      - hasquant
    ghc-options: -Wall
    source-dirs:
      - test
      - main/test
    main: QuantLib/MainTest.hs

executables:
  hasquant_example:
    when:
      - condition: flag(buildExample)
        then:
          buildable: True
        else:
          buildable: False
    ghc-options: -Wall
    dependencies:
      - hasquant
    source-dirs:
      - test
      - main/exe
    main: QuantLib/MainExample.hs
