#!/bin/sh
mkdir obj
ghc -outputdir obj -Wall -o E *.hs CashFlow/*.hs Index/*.hs Instrument/*.hs Internal/*.hs Math/*.hs TermStructure/*.hs Time/*.hs ../../test/QuantLib/Example/*.hs -lql -L. -optl-Wl,-rpath,. -pgml g++ Credit/*.hs
