#!/bin/sh
mkdir obj
ghc -outputdir obj -Wall -o T *.hs CashFlow/*.hs Index/*.hs Instrument/*.hs Internal/*.hs Math/*.hs TermStructure/*.hs ../../test/QuantLib/Test/*.hs Time/*.hs ../../test/QuantLib/Example/Bond.hs ../../test/QuantLib/Example/Repo.hs -lql -L. -pgml g++ -optl-Wl,-rpath,. Credit/*.hs ../../test/QuantLib/Example/FRA.hs ../../test/QuantLib/Example/Swap.hs ../../test/QuantLib/Example/FittedBondCurve.hs Method/*.hs FX/*.hs Model/*.hs
