#include <ql/time/calendar.hpp>

#include "ql.h"

/*
    <EnumeratedTypeGroup type='QuantLib::Calendar'>
      <includeFile>qlo/enumerations/factories/calendarfactory.hpp</includeFile>
      <constructor>false</constructor>
      <EnumeratedTypes>
        
        <EnumeratedType>
          <string>Calendar</string>
          <value>QuantLib::Calendar()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>NoCalendar</string>
          <value>QuantLib::Calendar()</value>
        </EnumeratedType>

        <!--too bad NullCalendar is actually a calendar-->
        <EnumeratedType>
          <string>Null</string>
          <value>QuantLib::NullCalendar()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>NullCalendar</string>
          <value>QuantLib::NullCalendar()</value>
        </EnumeratedType>

        <EnumeratedType>
          <string>TARGET</string>
          <value>QuantLib::TARGET()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Argentina::Merval</string>
          <value>QuantLib::Argentina(QuantLib::Argentina::Merval)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Australia</string>
          <value>QuantLib::Australia()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Brazil::Settlement</string>
          <value>QuantLib::Brazil(QuantLib::Brazil::Settlement)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Brazil::Exchange</string>
          <value>QuantLib::Brazil(QuantLib::Brazil::Exchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Canada::Settlement</string>
          <value>QuantLib::Canada(QuantLib::Canada::Settlement)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Canada::TSX</string>
          <value>QuantLib::Canada(QuantLib::Canada::TSX)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>China</string>
          <value>QuantLib::China()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>CzechRepublic::PSE</string>
          <value>QuantLib::CzechRepublic(QuantLib::CzechRepublic::PSE)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Denmark</string>
          <value>QuantLib::Denmark()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Finland</string>
          <value>QuantLib::Finland()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Germany::Eurex</string>
          <value>QuantLib::Germany(QuantLib::Germany::Eurex)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Germany::FrankfurtStockExchange</string>
          <value>QuantLib::Germany(QuantLib::Germany::FrankfurtStockExchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Germany::Settlement</string>
          <value>QuantLib::Germany(QuantLib::Germany::Settlement)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Germany::Xetra</string>
          <value>QuantLib::Germany(QuantLib::Germany::Xetra)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>HongKong::HKEx</string>
          <value>QuantLib::HongKong(QuantLib::HongKong::HKEx)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Hungary</string>
          <value>QuantLib::Hungary()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Iceland::ICEX</string>
          <value>QuantLib::Iceland(QuantLib::Iceland::ICEX)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>India::NSE</string>
          <value>QuantLib::India(QuantLib::India::NSE)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Indonesia::BEJ</string>
          <value>QuantLib::Indonesia(QuantLib::Indonesia::BEJ)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Indonesia::JSX</string>
          <value>QuantLib::Indonesia(QuantLib::Indonesia::JSX)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Italy::Exchange</string>
          <value>QuantLib::Italy(QuantLib::Italy::Exchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Italy::Settlement</string>
          <value>QuantLib::Italy(QuantLib::Italy::Settlement)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Japan</string>
          <value>QuantLib::Japan()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Mexico::BMV</string>
          <value>QuantLib::Mexico(QuantLib::Mexico::BMV)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>NewZealand</string>
          <value>QuantLib::NewZealand()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Norway</string>
          <value>QuantLib::Norway()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Poland</string>
          <value>QuantLib::Poland()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Russia</string>
          <value>QuantLib::Russia()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>SaudiArabia::Tadawul</string>
          <value>QuantLib::SaudiArabia(QuantLib::SaudiArabia::Tadawul)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Singapore::SGX</string>
          <value>QuantLib::Singapore(QuantLib::Singapore::SGX)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Slovakia::BSSE</string>
          <value>QuantLib::Slovakia(QuantLib::Slovakia::BSSE)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>SouthAfrica</string>
          <value>QuantLib::SouthAfrica()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>SouthKorea::KRX</string>
          <value>QuantLib::SouthKorea(QuantLib::SouthKorea::KRX)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Sweden</string>
          <value>QuantLib::Sweden()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Switzerland</string>
          <value>QuantLib::Switzerland()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Taiwan::TSEC</string>
          <value>QuantLib::Taiwan(QuantLib::Taiwan::TSEC)</value>
        </EnumeratedType>
        <EnumeratedType>
          <!-- clone of TARGET -->
          <string>EUR</string>
          <value>QuantLib::TARGET()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Turkey</string>
          <value>QuantLib::Turkey()</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>Ukraine::USE</string>
          <value>QuantLib::Ukraine(QuantLib::Ukraine::USE)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedKingdom::Exchange</string>
          <value>QuantLib::UnitedKingdom(QuantLib::UnitedKingdom::Exchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>London stock exchange</string>
          <!-- Clone for UnitedKingdom::Exchange -->
          <value>QuantLib::UnitedKingdom(QuantLib::UnitedKingdom::Exchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>LONDON</string>
          <!-- Clone for UnitedKingdom::Exchange -->
          <value>QuantLib::UnitedKingdom(QuantLib::UnitedKingdom::Exchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>GBP</string>
          <!-- Clone for UnitedKingdom::Exchange -->
          <value>QuantLib::UnitedKingdom(QuantLib::UnitedKingdom::Exchange)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedKingdom::Metals</string>
          <value>QuantLib::UnitedKingdom(QuantLib::UnitedKingdom::Metals)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedKingdom::Settlement</string>
          <value>QuantLib::UnitedKingdom(QuantLib::UnitedKingdom::Settlement)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedStates::GovernmentBond</string>
          <value>QuantLib::UnitedStates(QuantLib::UnitedStates::GovernmentBond)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedStates::NERC</string>
          <value>QuantLib::UnitedStates(QuantLib::UnitedStates::NERC)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedStates::NYSE</string>
          <value>QuantLib::UnitedStates(QuantLib::UnitedStates::NYSE)</value>
        </EnumeratedType>
        <EnumeratedType>
          <string>UnitedStates::Settlement</string>
          <value>QuantLib::UnitedStates(QuantLib::UnitedStates::Settlement)</value>
        </EnumeratedType>
      </EnumeratedTypes>
    </EnumeratedTypeGroup>
*/    
