services:
  app:
    build:
      context: .
    # target: development
      args:
        BOOST_VERSION: "1.91.0-1"
        QL_VERSION: "1.43"
    
    image: hasquant:default
    platform: linux/amd64
    init: true
    
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    volumes:
      - .:/app:delegated
      - stack-root:/root/.stack
      - stack-work:/app/.stack-work
    
    stdin_open: true
    tty: true
    #environment:
    #  - TERM=dumb
    #  - STACK_IN_CONTAINER=true

volumes:
  stack-root:
    name: hasquant_stack
  stack-work:
    name: hasquant_work
