QuantLib::PricingEngine* qlBinomialVanillaEngineAux(const char *tree, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps);
QuantLib::PricingEngine* qlBinomialConvertibleEngineAux(const char *tree, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps);

QuantLib::PricingEngine* qlMCVarianceSwapEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCHestonHullWhiteEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::HybridHestonHullWhiteProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, int controlVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCAmericanEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, int controlVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed, unsigned polynomOrder, QuantLib::LsmBasisSystem::PolynomType polynomType, unsigned nCalibrationSamples);
QuantLib::PricingEngine* qlMCBarrierEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, int isBiased, unsigned seed);
QuantLib::PricingEngine* qlMCDigitalEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> x0, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCDiscreteArithmeticAPEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, int controlVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCDiscreteArithmeticASEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCDiscreteGeometricAPEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCEuropeanEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned timeStepsPerYear, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCEuropeanGJRGARCHEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GJRGARCHProcess> x0, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCEuropeanHestonEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::HestonProcess> x0, unsigned timeSteps, unsigned timeStepsPerYear, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCHullWhiteCapFloorEngine1Aux(const char *rngtrait, boost::shared_ptr<QuantLib::HullWhite> model, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);
QuantLib::PricingEngine* qlMCPerformanceEngine1Aux(const char *rngtrait, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, int brownianBridge, int antitheticVariate, unsigned requiredSamples, double requiredTolerance, unsigned maxSamples, unsigned seed);

QuantLib::PricingEngine* qlFDAmericanEngineAux(const char *fdscheme, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned gridPoints, int timeDependent);
QuantLib::PricingEngine* qlFDBermudanEngineAux(const char *fdscheme, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned gridPoints, int timeDependent);
QuantLib::PricingEngine* qlFDEuropeanEngineAux(const char *fdscheme, const boost::shared_ptr<QuantLib::GeneralizedBlackScholesProcess> process, unsigned timeSteps, unsigned gridPoints, int timeDependent);

/* vim: set ft=cpp ff=unix ts=8 sts=2 sw=2 et: */
