Name:         qlc
Version:      0.1.0
Synopsis:     C wrappers for QuantLib library
Description:  Low-level C wrappers for QuantLib library, for use with quantlib package.
License:      BSD3
License-File: LICENSE
Author:       Sergey Khorev <sergey.khorev@gmail.com>
Maintainer:   Sergey Khorev <sergey.khorev@gmail.com>
Copyright:    Sergey Khorev 2012-2013

Category:     Finance
Cabal-Version:>=1.2
Tested-With:  GHC==7.4.2, GHC==7.6.2
--Homepage:
Build-type:   Custom

Extra-source-files:
              cbits/qlBond.cpp
              cbits/qlCalendar.cpp
              cbits/qlCouponPricer.cpp
              cbits/qlCredit.cpp
              cbits/qlCurrency.cpp
              cbits/qlDate.cpp
              cbits/qlDayCounter.cpp
              cbits/qlDefaultTS.cpp
              cbits/qlEnumerations.cpp
              cbits/qlForward.cpp
              cbits/qlIborIndex.cpp
              cbits/qlIndex.cpp
              cbits/qlInstrument.cpp
              cbits/qlInterestRate.cpp
              cbits/qlLeg.cpp
              cbits/qlMath.cpp
              cbits/qlMethod.cpp
              cbits/qlModel.cpp
              cbits/qlOption.cpp
              cbits/qlPeriod.cpp
              cbits/qlPricingEngine.cpp
              cbits/qlPricingEngineAux.cpp
              cbits/qlProcess.cpp
              cbits/qlQuote.cpp
              cbits/qlSchedule.cpp
              cbits/qlSettings.cpp
              cbits/qlSwap.cpp
              cbits/qlUtilities.cpp
              cbits/qlVolatilityTS.cpp
              cbits/qlYieldTS.cpp
              cbits/qlTSAux.cpp
              cbits/qlaux.h
              cbits/qlTSAux.h
              cbits/qlPricingEngineAux.h

Library
  Include-Dirs: cbits
  Install-Includes: ql.h
                    qlBond.h
                    qlCalendar.h
                    qlCouponPricer.h
                    qlCredit.h
                    qlCurrency.h
                    qlDate.h
                    qlDayCounter.h
                    qlDefaultTS.h
                    qlEnumerations.h
                    qlForward.h
                    qlIborIndex.h
                    qlIndex.h
                    qlInstrument.h
                    qlInterestRate.h
                    qlLeg.h
                    qlMath.h
                    qlMethod.h
                    qlModel.h
                    qlOption.h
                    qlPeriod.h
                    qlPricingEngine.h
                    qlProcess.h
                    qlQuote.h
                    qlSchedule.h
                    qlSettings.h
                    qlSwap.h
                    qlUtilities.h
                    qlVolatilityTS.h
                    qlYieldTS.h
  Build-Depends: base >= 4.5 && < 5

  X-Dll-Sources:
              cbits/qlBond.cpp
              cbits/qlCalendar.cpp
              cbits/qlCredit.cpp
              cbits/qlCouponPricer.cpp
              cbits/qlCurrency.cpp
              cbits/qlDate.cpp
              cbits/qlDayCounter.cpp
              cbits/qlDefaultTS.cpp
              cbits/qlEnumerations.cpp
              cbits/qlForward.cpp
              cbits/qlIborIndex.cpp
              cbits/qlIndex.cpp
              cbits/qlInstrument.cpp
              cbits/qlInterestRate.cpp
              cbits/qlLeg.cpp
              cbits/qlMath.cpp
              cbits/qlMethod.cpp
              cbits/qlModel.cpp
              cbits/qlOption.cpp
              cbits/qlPeriod.cpp
              cbits/qlPricingEngine.cpp
              cbits/qlPricingEngineAux.cpp
              cbits/qlProcess.cpp
              cbits/qlQuote.cpp
              cbits/qlSchedule.cpp
              cbits/qlSettings.cpp
              cbits/qlSwap.cpp
              cbits/qlUtilities.cpp
              cbits/qlVolatilityTS.cpp
              cbits/qlYieldTS.cpp
              cbits/qlTSAux.cpp

  X-Dll-Name: qlc
  X-Dll-Extra-Libraries: QuantLib

-- Source-Repository head

-- vim: set et ts=8 sts=2 sw=2:
