#!/bin/sh
mkdir obj
ghc -outputdir obj -hide-package qlc -hide-package quantlib -Wall -o E *.hs */*.hs ../../test/QuantLib/Example/*.hs ../../test/QuantLib/MainExample.hs -lql -L. -optl-Wl,-rpath,. -pgml g++
