#!/bin/sh
mkdir obj
ghc $* -outputdir obj -hide-package qlc -hide-package quantlib -Wall -o T *.hs */*.hs ../../test/QuantLib/Test/*.hs ../../test/QuantLib/Example/*.hs ../../test/QuantLib/MainTest.hs -lql -L. -pgml g++ -optl-Wl,-rpath,.
