#!/bin/sh
mkdir obj
ghc $* -outputdir obj -hide-package qlc -hide-package quantlib -Wall -o T *.hs */*.hs ../../test/QuantLib/Test/*.hs ../../test/QuantLib/Example/Bond.hs ../../test/QuantLib/Example/Repo.hs -lql -L. -pgml g++ -optl-Wl,-rpath,. ../../test/QuantLib/Example/FRA.hs ../../test/QuantLib/Example/Swap.hs ../../test/QuantLib/Example/FittedBondCurve.hs
