#!/bin/sh
mkdir obj
ghc -outputdir obj -Wall -o T *.hs CashFlow/*.hs Index/*.hs Instrument/*.hs Internal/*.hs Math/*.hs TermStructure/*.hs Test/*.hs Time/*.hs Example/Bond.hs -lql -L. -pgml g++ -optl-g -optl-Wl,-rpath,.
