#!/bin/sh
# Fetch a Stackage snapshot's cabal.config into cabal/stackage-<snapshot>.config,
# importable from a cabal.project file. Usage: tools/stackage-cabal-config.sh lts-24.56
set -eu

if [ $# -ne 1 ]; then
  echo "usage: $0 <snapshot, e.g. lts-24.56>" >&2
  exit 2
fi

snapshot=$1
root=$(git rev-parse --show-toplevel)
out="$root/cabal/stackage-$snapshot.config"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

curl -fsS "https://www.stackage.org/$snapshot/cabal.config" -o "$tmp"

# An unknown snapshot yields an HTML page, not an error status.
if ! grep -q '^with-compiler: ghc-' "$tmp" || ! grep -q '^constraints:' "$tmp"; then
  echo "$snapshot: response is not a Stackage cabal.config" >&2
  exit 1
fi

mkdir -p "$root/cabal"
{
  echo "-- Generated by tools/stackage-cabal-config.sh $snapshot on $(date -u +%Y-%m-%d)."
  cat "$tmp"
} > "$out"
echo "wrote ${out#"$root"/} ($(sed -n 's/^with-compiler: //p' "$out"))"
